### ISSUE TITLE
[question] handling multi region database best practices

### ISSUE THREAD

**Issue by u007** [gobuffalo/pop#181]
Hi,

Have anyone encounter the need to have regional base instances that may requires read replica of postgresql in those region and automatically write to central postgresql on update/insert/delete?

i know with serverless and aws, aurora does support this. but i belief this could be a costly setup.
I'm thinking maybe another 2 instances with its own read replica and pgpool that writes to central 
database. handling this manually might be troublesome to sync database across all instances...

and also, how do we modify database.yml to handle same deployment on different region?

Please share if you have any opinions :)

**Comment by sio4** [comment]
Hi, @u007 

How about CockroachDB?
Recently I just tested this cute distributed database built for the cloud environment and distributed service, and I found that the setup for this is quite simple and it works great across distributed nodes in point of distribution, replication and load balancing.

Pop also support cockroach.
I guess you might already consider this database. If so, can you share your experiences?

**Comment by u007** [comment]
hi @sio4 

guess we have to setup environment variables for the region of db to connect to ?

**Comment by sio4** [comment]
Oh, I just want to share my idea for globally distributed environment. If your service is distributed across the world, and it does not have heavy traffic yet, I think cockroach is good candidate against postgres.

It born to be distributed, easy to setup. For connection setting, we can use a LB since its symetric architecture. (There is no central master node for write, and it follows the work load.)

**Comment by u007** [comment]
yes im aware of it :) thanks for sharing
