### ISSUE TITLE
Convert fizz from mattn/anko to plush

### ISSUE THREAD

**Issue by markbates** [gobuffalo/pop#35]
Anko is continuingly breaking, and it’s out of our control. My suggestion is to switch to using Plush for fizz files. This way we have all the same advantages of using Plush, plus controlabilty, and the dropping of another dependency. 

To do this, though, I need some some help from the community. 

I need the craziest and outrageously complex .fizz files out there. Please post yours so I can start understanding the scale of issues involved with this change. 

I’m hoping that we can support existing .fizz files with zero changes to the syntax, but if there are changes that need to be made, we can release a tool to automate the process. 

Please post your .fizz files here please. :)

**Comment by barrongineer** [comment]
If I'm being honest, I try to stay away from fizz. Mostly due to editor support and everyone knows SQL. The only thing that would be nice is a way to override migrations for tests similar to how Spring Boot does it. For instance, migration in src/test/resources/... with the same name gets run instead since there are typically differences in syntax between mysql/postgres and h2/sqlite.

**Comment by stanislas-m** [comment]
I'm using SQL migrations too. @barrongineer For the syntax problems, I opened this issue on the old repo: https://github.com/markbates/pop/issues/145
Maybe it can cover your use-case.
