### ISSUE TITLE
Insert an expression or use NEXTVAL as value

### ISSUE THREAD

**Issue by zinefer** [gobuffalo/pop#482]
This is more of a question than an issue.

I would like to run an insert with a database calculated value, like:
```sql
INSERT INTO "users" ("id", "name") values (NEXTVAL("users_id_sequence"), "jake");
```

Is there some mechanism I can use to prepare an insert statement to use with a model or maybe a way to temporarily disable the quoting?

**Comment by sio4** [comment]
I guess you are thinking about automatically increasing ID values with `NEXTVAL`. When Fizz generates a migration for a supported database and if the ID is an integer type, it automatically makes them automatic. (`AUTO_INCREMENT` for mysql, `SERIAL` for postgresql, `AUTOINCREMENT` for sqlite3)

Also, when `Create` is called for a model, the ID field is ignored if the type is an integer and the values are configured automatically by the underlying database.

So in the boundary of Pop, except executing raw query which means everything is your own choice, you don't need to worry about it, and also you cannot set an ID.

I am not fully sure if my answer is fit to your question since you mentioned just a SQL example but I am answering within the context of Pop.
