### ISSUE TITLE
MySQL foreign key constraints break `mysql.TruncateAll()` (`TRUNCATE TABLE`) calls

### ISSUE THREAD

**Issue by TheOnlyRew** [gobuffalo/pop#49]
Taken alone, the title might not be a problem; MySQL intentionally disallows the truncation of tables referred to by foreign key constraints.

The problem is in the interaction between the above, and the setup steps taken by `buffalo test`. In gobuffalo/suite/model.go, the `SetupTest()` function calls `TruncateAll()` to ensure no data exists in the test tables prior to the suite's run. This can lead to;

```
model.go:26:
    Error Trace:    model.go:26
                        suite.go:61
                        suite.go:88
    Error:          Received unexpected error:
                    Error 1701: Cannot truncate a table referenced in a foreign key constraint ...
```

A (very) naive (and _very_ messy) work-around is to manually call `SET GLOBAL FOREIGN_KEY_CHECKS = 0;` in the *_test database before running `buffalo test`, but that might lead to false positives in the test suite.

A potentially less naive fix would be to modify [`mysql.TruncateAll()`](https://github.com/gobuffalo/pop/blob/master/mysql.go#L174) to call `SET SESSION FOREIGN_KEY_CHECKS = 0;` before executing the RawQuery, and re-setting the previous value (be it `0` or `1`) after the truncations are complete. I'm hesitant to open a PR implementing this fix for a couple reasons:

1. That might be a very bad idea.
    I'm no MySQL engineer, so I can't say for sure this is a reasonable thing to do. I assume it is, because my read of `SetupTest()` is that it's dropping _all_ data from the database, so there should be no data left to be orphaned, but... I don't know very MySQL well, so I don't know what corner cases (or not-so-corner cases) that setting might impact.
2. I'm not sure if it would be correct to modify `TruncateAll()` in that way.
    Again I assume it would be, but I'm not familiar enough with the consumers of Pop to know if that would lead to surprising behavior. If foreign key constraints are set, truncations _should_ fail. Would changing this function cause logic that should fail, to not fail? Would there be a clean way to add an argument or contextual setting to `TruncateAll()` that would let us control that behavior? Are there any uses of `TruncateAll` outside of `SetupTest()` for such a change to affect, anyway?

/shrug

**Comment by stanislas-m** [comment]
> That might be a very bad idea.
I'm no MySQL engineer, so I can't say for sure this is a reasonable thing to do. I assume it is, because my read of SetupTest() is that it's dropping all data from the database, so there should be no data left to be orphaned, but... I don't know very MySQL well, so I don't know what corner cases (or not-so-corner cases) that setting might impact.

Right now, I can't find a better option, even after using MySQL for years.

> I'm not sure if it would be correct to modify TruncateAll() in that way.
Again I assume it would be, but I'm not familiar enough with the consumers of Pop to know if that would lead to surprising behavior. If foreign key constraints are set, truncations should fail. Would changing this function cause logic that should fail, to not fail? Would there be a clean way to add an argument or contextual setting to TruncateAll() that would let us control that behavior? Are there any uses of TruncateAll outside of SetupTest() for such a change to affect, anyway?

To answer that question, we have to check the other DB behavior for pop supported dialects. If the other allow to truncate all the tables, even with foreign keys, we should do it.
