### ISSUE TITLE
did RawQuery paginate no longer runs count?

### ISSUE THREAD

**Issue by u007** [gobuffalo/pop#85]
hi,

previously rawquery was working with count,
but we suspect the latest update stopped working.
it returns 0 all the time, is this true?

**Comment by u007** [comment]
btw, im quite trouble by the direction of this project, can i have words on all merge request before merging?

**Comment by markbates** [comment]
Can you provide steps to reproduce?

In terms of reviewing PRs everyone is allowed to jump in PRs, please do so. If you have opinions and suggestions, please make them heard. 

In what particular ways are you troubled by the direction? Can you provide more clarity?

**Comment by u007** [comment]
im concern about naming, and also how rawquery used to work with eagerload initially, and later on it wasnt anymore

**Comment by stanislas-m** [comment]
@u007
As I said on other issues, I think `RawQuery` and others features are two separate worlds. This means it's not supposed to work with features like Eager loading, or `Count`, because it means we'll have to rewrite the raw query.

That's my point of view, and I think the main problem here is about having a bug which transforms to a feature. So to begin with, we should write a specification about how it should work.

If you disagree, I'm all ears. :) Maybe it's just about providing a missing feature, so you don't need to rely on a workaround.

**Comment by u007** [comment]
hi @stanislas-m sometimes we need custom query to join tables for query to populate result into a struct (not the original query) and it should be able to detect other tables that it is linked from the original struct.
i think this is a norm in rails and it works.
i wanted to help, but which file should i start my dive from?

**Comment by u007** [comment]
i realized it is working with the latest master branch, did someone fixed it?

https://github.com/gobuffalo/pop/pull/98
