### ISSUE TITLE
model struct tag validator

### ISSUE THREAD

**Issue by petar-dambovaliev** [gobuffalo/pop#94]
https://github.com/gobuffalo/pop/pull/96

Proof of concept.

**Comment by PetarAtanasov** [comment]
@markbates tests and benchmarks added. It's worth checking out.

**Comment by stanislas-m** [comment]
Given the conversation in #96, I'm not sure the feature scope is clearly defined. So I'll try to define it here:
- You're trying to build some validation for models structs tags, because (for instance) if you use the same mapping with the `db` tag with two different fields, it doesn't work; but the error is not obvious.
- The goal of this feature is to provide more info to the dev, so such errors can be avoided.
- The feature must be presented as a public API first, like other commands. This way, it can be used as a library, and embedded in other projects (like Buffalo).
- It will be exposed as a CLI service too, calling the public API.
- `validate` is deeply associated with https://github.com/gobuffalo/validate in Buffalo ecosystem, so using this term will be confusing. A more appropriate verb can be `lint` or `vet`, since similar Go tools are already using this terminology.
- Each tag validation should be exposed as a separate rule. This way, the user can choose the linter rules to apply.
- By default, all the rules must be applied (if none provided).
- Concurrency is not the priority, and can cause problems since the https://github.com/gobuffalo/validate package already provides a concurrency system to apply the rules.
 - https://github.com/gobuffalo/validate already provides a way to define "rules", so it should be considered as a base to define the rules, to not reinvent the wheel.

@markbates If I'm missing a point, or if something is wrong, feel free to fix this spec. :)
@PetarAtanasov Until we agree on a spec, I think it's not worth to add/modify your code. I prefer you don't loose time patching your code again and again, and designing features are a good way to learn too! :)
